### ISSUE TITLE
Will not load certain variables

### ISSUE THREAD

**Issue by bludrop** [helpers/handlebars-helper-compose#7]
I am using the compose helper in a layout template file to load a list of .md files from a different target/collection.

The variables defined in the YFM of the .md files are loading correctly ({{title}} and {{section}}, for example). {{ext}} is also loading. Other helpers, such as {{pagename}}, {{filename}}, and {{base name}}, are not loading anything.

The {{relative } helper also doesn't seem to be working when used with {{compose}}.

Are these helpers supposed to work when used with {{compose}}? Or is there a different way to use them?

**Comment by jonschlinkert** [comment]
This might be a bug, but just in case have you tried `{{../filename}}` etc?  thanks

**Comment by bludrop** [comment]
Yeah, I tried ../ and other ways to change the context. Nothing that I tried seemed to work. Thanks for looking into it

**Comment by jonschlinkert** [comment]
Please take a look at the changes that I pushed up. I bumped the version to 0.2.0, but I'll need to make a few more changes before it's ready for prime time, so I recommend that you only use it for testing. 

I still need to calculate relative paths for "composed" files and add the variable for that to the context. I also want to add a function that will automatically expose any variable from the YAML front matter of composed files as variables on the context, so that any variable can be used with this syntax: `{{@foo}}` (this is a special syntax for variables on the `data` object)

**Comment by bludrop** [comment]
Thanks, I will try it out. Looking forward to the further changes.

Is the special variable syntax `{{@foo}}` documented anywhere? (How is this different than `{{foo}}`?)

**Comment by jonschlinkert** [comment]
> Is the special variable syntax `{{@foo}}` documented anywhere?

It's a very sparsely documented Handlebars feature that makes use of `Handlebars.createFrame`. Whereas `{{foo}}` could just be a variable on the original context, `createFrame` allows you to inject private variables into templates, so that the data is only available in the block helper's child template and not in the original context. In a nutshell it helps avoid collisions and/or mutating upstream variables. So if someone already has a `content` variable on the context, they could still use `{{@content}}` without issues

**Comment by jonschlinkert** [comment]
Are we in good shape on this?

**Comment by bludrop** [comment]
I can't get it to work with 0.2.3. I am receiving an error from grunt:

`Warning: Cannot read property 'src' of undefined Use --force to continue.`

This occurred when I just installed the new module and tried to run grunt with almost no other changes (aside from updating the name of the module and adding the `@` variables)

**Comment by jonschlinkert** [comment]
Did you adds the `src` property for your file paths? e.g. `{{#compose src="foo/*.hbs"}}`

**Comment by bludrop** [comment]
Yup.

None of these are working:
`{{ #compose src="src/issues/**/*.md" }}` (what I had the before the upgrade)
`{{#compose src="**/*.md" }}`
`{{#compose cwd="src/issues/" src="**/*.md" }}`

**Comment by jonschlinkert** [comment]
How are paths defined in the Gruntfile? Are you using src-dest pairings? Files object, or files array? If files array, are you defining a cwd in the gruntfile?

**Comment by jonschlinkert** [comment]
Hmm, I'm not sure what's breaking have you looked at the tests? I'll need something more descriptive to try to debug this. also:

> what I had the before the upgrade

Before 0.2.0 there was no `src` property required, it was just `{{#compose "**/*.md" }}`, which is what you had in your examples. So just to be clear, are you saying that you did successfully upgrade to 0.2.0 and start using `{{#compose src="**/*.md" }}`, but then after 0.2.3 it broke?

**Comment by bludrop** [comment]
I'm using src-dest pairings:

``` javascript
       issues: {
        options: {
          layout: 'issue.hbs',
        },
        expand: true,
        cwd: '<%= build.src %>/issues/',
        src: ['../index.hbs','**/index.hbs','!_*/**'], //only do index.hbs
        dest: '<%= build.out %>/issues/'
      },
```

Yes, I added the src after the upgrade. It is not compiling the page with the `src=" "`.

I didn't get a chance to upgrade to 0.2.0. I only installed 0.2.3 from npm (with the new name) and uninstalled `helper-compose`

**Comment by bludrop** [comment]
This is the site before adding in the `src=" "` for the 0.2.x version:
https://github.com/bludrop/ptmag-archive

**Comment by doowb** [comment]
@bludrop I'm assuming [this line](https://github.com/bludrop/ptmag-archive/blob/master/src/_layouts/issue.hbs#L39) is from before the upgrade.

Also, did you double check to make sure that you're getting the correct version? I usually delete my `node_modules` folder, then `npm cache clear`, then `npm i` to make sure everything is the latest. And double check to make sure the old name/version isn't referenced in the `package.json` file. All of these things have bit me before.

**Comment by jonschlinkert** [comment]
@bludrop I forked your project and I'm trying to get it building now. would you be mind if I do a pr with the build config updated to make it easier to follow?

**Comment by bludrop** [comment]
@doowb yes that has been changed. I didn't delete the `node_modules` but I did a `npm cache clear` and an `npm update`. I guess I could erase everything and install again, but that seems unnecessary...?

And yes the new version is referenced in the `package.json`.

@jonschlinkert thanks. Sure (I'm sort of new to this so I'm not quite sure how the PRs work, but I imagine I can figure it out)

**Comment by jonschlinkert** [comment]
Great, here is your first PR then! https://github.com/bludrop/ptmag-archive/pull/1 :-)

It was a config problem, nothing to do with the helper. also you were using the old helper there still, which was named "helper-compose". It has been renamed to "handlebars-helper-compose". this wasn't the cause either, but now it's updated

I added `_config.yml` to the project root for you to update site variables there instead of having so many different "root" variables in the grunt config. it's your project so obviously feel free to change anything I did, I just wanted to make it more clear what what happening. hope this helps. 

oh, btw it looks like usemin or some other part of the build is chopping off the closing tags of your HTML. That plugin is super hacky, so just be aware that it's happening.

**Comment by bludrop** [comment]
Hmm interesting. I will merge it and take a look. Hopefully it works.

Thanks for your help!

**Comment by bludrop** [comment]
@jonschlinkert Two questions:
1. I noticed that you left the variables inside the `{{compose}}` tags without the `@`. Will they work like that? Is it recommended, though, to use the `@`?
2. It looks like there were a lot of 'formatting' changes in some of the files in the pull request. Was there a grunt plugin that did that or did you make the changes by hand (or something else)? Just wondering...

**Comment by jonschlinkert** [comment]
> I noticed that you left the variables inside the `{{compose}}` tags without the `@`

I didn't really touch anything inside the blocks, so I'm not sure

>  It looks like there were a lot of 'formatting' changes in some of the files

yes, it's just a lot easier to see what's causing issues when the code is formatted. 

> Was there a grunt plugin that did that or did you make the changes by hand (or something else)? Just wondering...

I manually formatted most of it, but I also use sublime text plugins. I don't even remember which one is responsible for the formatting. I just looked and can't track which plugin is adding the options for formatting, but there are several that do it

**Comment by jonschlinkert** [comment]
Oh, I also use https://github.com/jonschlinkert/grunt-prettify for formatting dest files sometimes, but only during development

**Comment by bludrop** [comment]
Okay, now that the sources of the issues have been sorted out, I think this can be closed. I can confirm that the `{{@pagename}}` `{{@filename}}` `{{@basename}}` and `{{@dirname}}` variables work. Thanks!
